---
title: "L01 Review"
subtitle: "Data Science III (STAT 301-3)"
author: "YOUR NAME HERE"
output: 
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
---

## Overview

The goal of this lab is to review vocabulary and concepts from the Data Science II (STAT 301-2).

## Questions

Please complete the following questions. Be sure that your solutions are clearly indicated and that your document is neatly formatted.


### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

<br>

### Question 2

Explain the difference between supervised and unsupervised learning.

<br>

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

1. Descriptive Models: **YOUR DESCRIPTION**

2. Inferential Models: **YOUR DESCRIPTION**

3. Predictive Models: **YOUR DESCRIPTION**

<br>

### Question 4 

We can describe predictive models by how they were developed as being either mechanistic or empirically driven. 

a. What does it mean to be a mechanistic model?

b. What does it mean to be an empirically driven model?

c. How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

d. In general, is a mechanistic or empirically driven model easier to understand? Explain.

e. How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

f. Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

<br>

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

<br>

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

<br>

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it.

<br>

### Question 8 

Briefly describe model tuning and why we use it.

<br>

### Question 9 

What are two common performance metrics when dealing with a regression ML problem?

What are two common performance metrics when dealing with a classification ML problem?

<br>

### Question 10

A political candidate's campaign has detailed voter history data for their constituents. The campaign is interested in two questions:

1. Given a voter's profile/data how likely is it that they will vote in favor of the candidate?

1. How would a voter's likelihood of support for the candidate change if they had personal contact with the candidate?

Classify each question/problem as either prediction or inferential. Explain your reasoning for each

<br>

## Github Repo Link

[YOUR GITHUB URL](TEXT FOR YOUR GITHUB URL){target="_blank"}
